# Paths
xdsl-opt: xdsl-opt # from virtualenv
mlir-opt: /usr/bin/mlir-opt-16
mlir-translate: /usr/bin/mlir-translate-16
cc: /tools/riscv-llvm/bin/clang++
llvm-mc: /tools/riscv-llvm/bin/llvm-mc
spike: /opt/snitch-spike/bin/spike-dasm
vltsim: snitch_cluster.vlt
gentrace: /opt/snitch_cluster/util/trace/gen_trace.py
xdsl_commit: /src/xdsl_commit.txt

# Flags
asflags:
  - -menable-experimental-extensions
  - -mcpu=snitch
  - -mabi=ilp32d
  - -mcmodel=medany
  - -ftls-model=local-exec
  - -ffast-math
  - -fno-builtin-printf
  - -fno-common
  - -O3
  - -D__DEFINED_uint64_t
  - -I/opt/snitch_cluster/sw/runtime/src
  - -I/opt/snitch_cluster/sw/runtime/impl
  - -I/opt/snitch_cluster/sw/runtime/api
  - -I/opt/snitch_cluster/sw/runtime/src/omp/
  - -I/opt/snitch_cluster/sw/runtime/api/omp/
cflags:
  - -Wno-unused-command-line-argument
  - -menable-experimental-extensions
  - -mcpu=snitch
  - -mabi=ilp32d
  - -mcmodel=medany
  - -ftls-model=local-exec
  - -ffast-math
  - -fno-builtin-printf
  - -fno-common
  - -O3
  - -D__DEFINED_uint64_t
  - -I/opt/snitch_cluster/sw/runtime/src
  - -I/opt/snitch_cluster/sw/runtime/impl
  - -I/opt/snitch_cluster/sw/runtime/api
  - -I/opt/snitch_cluster/sw/runtime/src/omp/
  - -I/opt/snitch_cluster/sw/runtime/api/omp/
ldflags:
  - -fuse-ld=/tools/riscv-llvm/bin/ld.lld
  - -nostartfiles
  - -nostdlib
  - -L/tools/riscv-llvm/lib/clang/15.0.0/lib/
  - -L/opt/snitch_cluster/sw/runtime/
  - -L/opt/snitch_cluster/sw/runtime/impl
  - -L/opt/snitch_cluster/sw/runtime/build
  - -T/opt/snitch_cluster/sw/runtime/base.ld
  - -lc
  - -lsnRuntime
  - -lclang_rt.builtins-riscv32
llvm-mcflags:
  - -disassemble
  - -mcpu=snitch
xdsl-passes:
  - test-lower-linalg-to-snitch
mlir-opt-flags-linalg:
  - -opaque-pointers=0
  - --linalg-generalize-named-ops
  - --eliminate-empty-tensors
  - -empty-tensor-to-alloc-tensor
  - --one-shot-bufferize='bufferize-function-boundaries function-boundary-type-conversion=identity-layout-map'
  - --canonicalize
mlir-opt-flags-scf:
  - --convert-linalg-to-loops
  - --lower-affine
  - --canonicalize
  - --convert-scf-to-cf
  - --canonicalize
  - --cse
  - --convert-math-to-llvm
  - --convert-memref-to-llvm='use-generic-functions index-bitwidth=32'
  - --convert-func-to-llvm='use-bare-ptr-memref-call-conv index-bitwidth=32'
  - --convert-index-to-llvm=index-bitwidth=32
  - --convert-cf-to-llvm=index-bitwidth=32
  - --convert-arith-to-llvm=index-bitwidth=32
  - --reconcile-unrealized-casts
