[project]
name = "riscv-paper-experiments"
version = "0.1.0"
description = "RISC-V paper experiments (Snitch toolchain, xDSL pipelines)"
requires-python = ">=3.11"
dependencies = [
    "pandas",
    "seaborn",
    "numpy",
    "snakemake==8.14.0",
    "xdsl @ git+https://github.com/szerdick/xdsl.git@3727f0a8acf8e91c0b985383f205be9e6ad62405",
]
