name: Run experiments

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-experiments:
    runs-on: ubuntu-latest
    container: ghcr.io/nazavode/snitch-toolchain:2.3
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Run experiments
        run: scripts/run.sh --abort-on-error --tag cirun
      - name: PR comment with CSV file
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: results/cycles_cirun.csv
      - name: PR comment with PDF file
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: results/cycles_cirun.pdf
