name: Show pretty table

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-experiments:
    runs-on: ubuntu-latest
    container: ghcr.io/opencompl/snitch-toolchain:latest
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          submodules: recursive
      - name: Check pivoted is up to date
        run: cd kernels
          make -q pivoted.csv
      - name: Read Cycles CSV
        id: cycles-csv
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: kernels/pivoted.csv
      # - name: Create MD
      #   uses: petems/csv-to-md-table-action@master
      #   id: cycles-csv-table-output
      #   with:
      #     csvinput: ${{ steps.cycles-csv.outputs.content }}
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            ${{steps.cycles-csv.outputs.content}}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]" # The user.login for temporary GitHub tokens
          allow-repeats: true
      - name: Read FPU CSV
        id: fpu-csv
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: kernels/pivoted_fpu.csv
      # - name: Create MD
      #   uses: petems/csv-to-md-table-action@master
      #   id: fpu-csv-table-output
      #   with:
      #     csvinput: ${{ steps.fpu-csv.outputs.content }}
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            ${{steps.fpu-csv.outputs.content}}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]" # The user.login for temporary GitHub tokens
          allow-repeats: true
