name: Show pretty table

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-experiments:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/opencompl/snitch-toolchain:latest
      options: --volume ${{ github.workspace }}:/src
    steps:
      - uses: actions/checkout@v3.5.0
        with:
          submodules: recursive
      - name: Install dependencies in venv
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -e /src/xdsl
          pip install -r /src/scripts/requirements.txt
      - name: Clean and make pivoted
        run: |
          . venv/bin/activate
          cd kernels
          make clean
          make pivoted.csv
      - name: Check pivoted has not changed
        uses: tj-actions/verify-changed-files@v20
        id: verify-changed-files
        with:
          files: |
              pivoted.csv
      - name: Run step only when any of the above files change.
        if: steps.verify-changed-files.outputs.files_changed == 'true'
        env:
          CHANGED_FILES: ${{ steps.verify-changed-files.outputs.changed_files }}
        run: |
          echo "Changed files: $CHANGED_FILES"
      - name: Read Cycles CSV
        id: cycles-csv
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: kernels/pivoted.csv
      # - name: Create MD
      #   uses: petems/csv-to-md-table-action@master
      #   id: cycles-csv-table-output
      #   with:
      #     csvinput: ${{ steps.cycles-csv.outputs.content }}
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            ${{steps.cycles-csv.outputs.content}}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]" # The user.login for temporary GitHub tokens
          allow-repeats: true
      - name: Read FPU CSV
        id: fpu-csv
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: kernels/pivoted_fpu.csv
      # - name: Create MD
      #   uses: petems/csv-to-md-table-action@master
      #   id: fpu-csv-table-output
      #   with:
      #     csvinput: ${{ steps.fpu-csv.outputs.content }}
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            ${{steps.fpu-csv.outputs.content}}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]" # The user.login for temporary GitHub tokens
          allow-repeats: true
