name: Show pretty table

on:
  push:
    branches:
      - main
  pull_request:

# BEWARE: Github broke CI for everyone using older distros
# (including Ubuntu LTS):
# https://github.com/actions/checkout/issues/1590
# To make sure the CI doesn't break, export this variable
# and stick to actions/checkout@v3.
# This ugly hack is still expected to break at some point.
env:
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true

jobs:
  run-experiments:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/opencompl/snitch-toolchain:2.10
      options: --volume ${{ github.workspace }}:/src
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install dependencies in venv
        run: |
          python3 -m venv venv
          . venv/bin/activate
          pip install -r /src/requirements.txt
      - name: Clean and make pivoted
        run: |
          . venv/bin/activate
          cp results/pivoted.csv results/pivoted_old.csv.txt
          make clean
          make
      - name: Check pivoted has not changed
        run: |
          cd /src/
          ./scripts/nodiff.sh results/pivoted.csv results/pivoted_old.csv.txt
      - name: Read Cycles CSV
        id: cycles-csv
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: results/pivoted.csv
      # - name: Create MD
      #   uses: petems/csv-to-md-table-action@master
      #   id: cycles-csv-table-output
      #   with:
      #     csvinput: ${{ steps.cycles-csv.outputs.content }}
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            ${{steps.cycles-csv.outputs.content}}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]" # The user.login for temporary GitHub tokens
          allow-repeats: true
      - name: Read FPU CSV
        id: fpu-csv
        uses: juliangruber/read-file-action@v1.1.6
        with:
          path: results/pivoted_fpu.csv
      # - name: Create MD
      #   uses: petems/csv-to-md-table-action@master
      #   id: fpu-csv-table-output
      #   with:
      #     csvinput: ${{ steps.fpu-csv.outputs.content }}
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            ${{steps.fpu-csv.outputs.content}}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]" # The user.login for temporary GitHub tokens
          allow-repeats: true
