name: Show pretty table

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-experiments:
    runs-on: ubuntu-latest
    container: ghcr.io/nazavode/snitch-toolchain:latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Check pivoted is up to date
        run: cd kernels
          make -q pivoted.csv
      - name: Read CSV
        id: csv
        uses: juliangruber/read-file-action@v1
        with:
          path: kernels/pivoted.csv
      - name: Create MD
        uses: petems/csv-to-md-table-action@master
        id: csv-table-output
        with:
          csvinput: ${{ steps.csv.outputs.content }}
      - uses: mshick/add-pr-comment@v1
        with:
          message: |
            ${{steps.csv-table-output.outputs.markdown-table}}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          repo-token-user-login: "github-actions[bot]" # The user.login for temporary GitHub tokens
          allow-repeats: true
